# Docker Compose Librairie
services:
  librairie-api:
    build: .
    container_name: erp-librairie-api
    ports:
      - "8013:8000"
    networks:
      - erp-librairie-network
networks:
  erp-librairie-network:
    driver: bridge
