# Docker Compose Restaurant
services:
  restaurant-api:
    build: .
    container_name: erp-restaurant-api
    ports:
      - "8010:8000"
    environment:
      - DATABASE_URL=postgresql://erpuser:erppassword@postgres:5432/erp_restaurant
    networks:
      - erp-restaurant-network
networks:
  erp-restaurant-network:
    driver: bridge
